name: Build and test of Java Project
 
on: [push]
 
jobs:
 build:
   runs-on: ubuntu-latest
 
   steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 1.8
       uses: actions/setup-java@v1
       with:
         java-version: 1.8
     - name: echo a string
       run: echo "Hello world"
     - name: echo a comandos
       run: |
        pwd
        mkdir prueba
        cd prueba
        cat > hola.txt
        ls 
     - name: echo a tail
       run: |
        tail texto.txt 
     - name: echo a cp
       run: |
        mkdir prueba-cp
        cp texto.txt /home/runner/work/Florian-6-11-Administracion-de-sistemas-y-redes/Florian-6-11-Administracion-de-sistemas-y-redes/prueba-cp
     - name: echo a mv
       run: |
        touch archivo.txt
        mv archivo.txt /home/runner/work/Florian-6-11-Administracion-de-sistemas-y-redes/Florian-6-11-Administracion-de-sistemas-y-redes/prueba-cp
     - name: echo a estructura
       run: |
        cd ../../
        mkdir alumno
        cd alumno
        mkdir informatica
        cd informatica
        mkdir alumnosinf
        mkdir profesoresinf
        mkdir aulainf
        cd alumnosinf
        mkdir notasinf
       
